In [67]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [68]:
tf.__version__

'2.4.0'

In [69]:
dataset= pd.read_csv(r"C:\Users\Mansi Panchal\Desktop\py\ANN model\Churn_Modelling.csv")
x= dataset.iloc[:, 3:-1].values # will take column 4th to second last
y= dataset.iloc[:, -1].values

In [70]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [71]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [72]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
x[:,2]= le.fit_transform(x[:,2])

In [73]:
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [74]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct= ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[1])],remainder="passthrough")
x=np.array(ct.fit_transform(x))

In [17]:
x

array([[1.0, 0.0, 1.0, ..., 1, 1, 101348.88],
       [1.0, 0.0, 0.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 1.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 1.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 1.0, ..., 1, 0, 38190.78]], dtype=object)

### Train Test Split

In [75]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.5,random_state=0)

### Feature Scaling

In [76]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [77]:
ann= tf.keras.models.Sequential()

In [78]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu")) #input layer and first hidden layer

In [79]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu")) #second hidden layer

In [80]:
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid")) #output layer

### Training the ANN

In [81]:
ann.compile(optimizer= "adam",loss= "binary_crossentropy",metrics=["accuracy"])

In [82]:
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
157/157 [==============================] - 1s 722us/step - loss: 0.7720 - accuracy: 0.4250
Epoch 2/100
157/157 [==============================] - 0s 706us/step - loss: 0.5048 - accuracy: 0.7943
Epoch 3/100
157/157 [==============================] - 0s 588us/step - loss: 0.4634 - accuracy: 0.7983
Epoch 4/100
157/157 [==============================] - 0s 633us/step - loss: 0.4406 - accuracy: 0.8052
Epoch 5/100
157/157 [==============================] - 0s 594us/step - loss: 0.4428 - accuracy: 0.7924
Epoch 6/100
157/157 [==============================] - 0s 743us/step - loss: 0.4172 - accuracy: 0.8075
Epoch 7/100
157/157 [==============================] - 0s 660us/step - loss: 0.4074 - accuracy: 0.8157
Epoch 8/100
157/157 [==============================] - 0s 754us/step - loss: 0.4192 - accuracy: 0.8181
Epoch 9/100
157/157 [==============================] - 0s 630us/step - loss: 0.4178 - accuracy: 0.8151
Epoch 10/100
157/157 [==============================] - 0s 563us/step - l

157/157 [==============================] - 0s 582us/step - loss: 0.3273 - accuracy: 0.8720
Epoch 80/100
157/157 [==============================] - 0s 588us/step - loss: 0.3319 - accuracy: 0.8661
Epoch 81/100
157/157 [==============================] - 0s 750us/step - loss: 0.3453 - accuracy: 0.8613
Epoch 82/100
157/157 [==============================] - 0s 600us/step - loss: 0.3314 - accuracy: 0.8684
Epoch 83/100
157/157 [==============================] - 0s 582us/step - loss: 0.3467 - accuracy: 0.8619
Epoch 84/100
157/157 [==============================] - 0s 560us/step - loss: 0.3337 - accuracy: 0.8631
Epoch 85/100
157/157 [==============================] - 0s 575us/step - loss: 0.3428 - accuracy: 0.8654
Epoch 86/100
157/157 [==============================] - 0s 636us/step - loss: 0.3358 - accuracy: 0.8685
Epoch 87/100
157/157 [==============================] - 0s 588us/step - loss: 0.3404 - accuracy: 0.8700
Epoch 88/100
157/157 [==============================] - 0s 575us/step - loss:

In [83]:
# to predict an outcome from model
print(ann.predict(sc.transform([[1, 0, 1, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))) #will give probability of leaving bank(sigmoid fn)

[[0.05489132]]


In [87]:
print(ann.predict(sc.transform([[1, 0, 1, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))>0.5) #threshold probability

[[False]]


### Predicting the Test set results

In [89]:
y_pred=ann.predict(x_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 1]
 [0 0]]


### Confusion Matrix

In [90]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[3757  209]
 [ 507  527]]


0.8568